version: '2'  
services:  
  users-service:
    build: ./users_service
    ports:
      - "8123:8123"
    depends_on:
      - user_db
    environment:
      - DATABASE_HOST=user_db
  user_db:
    build: ./users_service/database