version: '2'  
services:
  #api-gateway
  gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - users-service
      - meetings-service
  #users-servcive
  users-service:
    build: ./users_service
    ports:
      - "8123:8123"
    expose:
      - "8123"
    depends_on:
      - user_db
    environment:
      - DATABASE_HOST=user_db
  user_db:
    build: ./users_service/database
    ports:
      - "3306:3306"
  #meetings-service
  meetings-service:
    build: ./meetings_service
    ports:
      - "8124:8124"
    expose:
      - "8124"
    depends_on:
      - meetings_db
    external_links:
      - meetings_db:mysql
    environment:
      - DATABASE_HOST=meetings_db
  meetings_db:
    build: ./meetings_service/database
    ports:
      - "3307:3306"
  #assistance-service
  assistance-service:
    build: ./assistance_service
    ports:
      - "8125:8125"
    expose:
      - "8125"
    depends_on:
      - assistance_db
    external_links:
      - assistance_db:mysql
    environment:
      - DATABASE_HOST=assistance_db
  assistance_db:
    build: ./assistance_service/database
    ports:
      - "3308:3306"
  #grades-service
  grades-service:
    build: ./grades_service
    ports:
      - "8126:8126"
    expose:
      - "8126"
    depends_on:
      - grades_db
    external_links:
      - grades_db:mysql
    environment:
      - DATABASE_HOST=grades_db
  grades_db:
    build: ./grades_service/database
    ports:
      - "3309:3306"